[en]
  title = "YC's Blog"
  languageName = "English"
  weight = 1
  languagedir = "en"
  contentdir = "content/en"

[cn]
  title = "YC 部落格"
  languageName = "中文"
  weight = 2
  languagedir = "cn"
  contentdir = "content/cn"