[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2
    
[[main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "portfolio"
  weight = 3

#   [[main]]
#   identifier = "archive"
#   name = "archive"
#   url = "archive"
#   weight = 4

# [[main]]
#   identifier = "gallery"
#   name = "gallery"
#   url = "gallery"
#   weight = 3
    
# [[main]]
#   parent = "gallery"
#   name = "cartoon"
#   url = "gallery/cartoon"

# [[main]]
#   parent = "gallery"
#   name = "photo"
#   url = "gallery/photo"