project:
  type: website

website:
  title: "Yao-Chung"
  site-url: "https://ferygood.github.io"
  google-analytics: "UA-181333208-1"
  page-footer: "Yao-Chung Chen © All Rights Reserved. 2022"
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: posts/posts.qmd
      - text: Projects
        href: https://google.com
      - text: Resume
        href: https://google.com
        
      - icon: github
        href: https://github.com/ferygood
      - icon: linkedin
        href: https://twitter.com
      - icon: envelope
        href: mailto:yaochung41@gmail.com
        
format:
  html:
    theme: minty
    css: styles.css

editor: visual

